version: 0

domains:
  main:
    description: The one and only domain
    owner: mike@earthly.dev
  main.child:
    description: The child of main
    owner: mike@earthly.dev

components:
  github.com/my-org/my-repo:
    owner: mike@earthly.dev
    domain: main
    branch: main
    tags: [go, backend]

collectors:
  - uses: ./go-version
    on: ["domain:main"]
  - uses: github://projects/snippets-2/go-version@main
    on: [go]
  - uses: github://projects/snippets-2/earthly-version@main
    on: [backend]
  - runBash: lunar collect go_version_1 $("go version")
    on: ["domain:main"]
    hook:
      type: ci-before-command
      pattern: ^go build.*

policies:
  - mainBash: ./main.bash
    on: ["domain:main"]
