version: 0

domains:
  main:
    description: The one and only domain
    owner: mikejholly@gmail.com
  main.child:
    description: The child of main
    owner: mikejholly@gmail.com

components:
  github.com/my-org/my-repo:
    owner: mikejholly@gmail.com
    domain: main
    branch: main
    tags: [go, backend]

collectors:
  - uses: ./go-version
    on: ["domain:main"]
  - uses: github://mikejholly/snippets-2/go-version@main
  - uses: github://mikejholly/snippets-2/earthly-version@main
  - runBash: lunar collect go_version $("go version")
    on: ["domain:main"]
    hook:
      type: ci-before-command
      pattern: ^go build.*

policies:
  - mainBash: ./main.bash
    on: ["domain:main"]
